version: '3.5'

services:
  whatsapp.backend:
    container_name: whatsapp_backend
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes: 
      - ./docker/startup.sh:/startup.sh
      - ./:/api
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 9001:9001
      - 8080:8080
    entrypoint: 
      - '/startup.sh'
    working_dir: '/api'
